name: Custom GH Action
run-name: AAAPLLLmim executed byx
runs: 
  using: composite
  steps:
    - name: s1a 
      run: |
           echo 1a
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: s2a 
      id: s2a
      run: python src/beta.py
    - name: s3a 
      run: echo "eu s3a citesc din s2a ENV."
