name: Custom GH Action
run-name: AAAPLLLmim executed byx
runs: 
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: s2a 
      id: s2a
      run: python src/beta.py
      shell: bash
    - name: s3a 
      run: python alpha.py
      shell: bash
