name: Vine cmd din worflow V3
on: workflow_dispatch
jobs:
  mimbuildA:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: instalez deps
      run: |
         python -m pip install --user pdm
    - name: check them
      run: |
         echo `pdm --version`
    - name: mk rooom
      run: |
         mkdir -p build/lib
         echo "gata domle avem libi"
      shell: bash
    - name: builddd
      run: |
         pdm build --dest build/lib
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact.whl
        path: build/lib
        overwrite: true
    - name: try it
      run: python src/beta.py
    - name: s399a 
      run: echo "eu s3a citesc din s2a ENV...${{ steps.s2a.outputs.URLSERV}}"
    - name: Dump steps context--j1
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
###
  logoss:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
