name: Vine cmd din worflow
on: workflow_dispatch
jobs:
  mimbuildA:
    runs-on: ubuntu-latest
    steps:
    - name: s1a 
      run: |
           echo 1a
           echo ${{ env.PIPE }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: instalez deps
      run: |
         python -m pip install --user pdm
    - name: s399a 
      run: echo "eu s3a citesc din s2a ENV...${{ steps.s2a.outputs.URLSERV}}"
