name: mimcid
run-name: PLLLmim executed by ${{ github.actor }}
on: workflow_dispatch
jobs:
  mimbuildA:
    runs-on: ubuntu-latest
    steps:
    - name: s1a 
      run: |
           echo 1a
           echo ${{ env.PIPE }}
    - name: s2a 
      id: s2a
      run: echo "URLSERV=https://call.now" >> $GITHUB_OUTPUT
    - name: s3a 
      run: echo "eu s3a citesc din s2a ENV...${{ steps.s2a.outputs.URLSERV}}"
       
    

  mimpackB:
    runs-on: ubuntu-latest
    steps:
    - name: s1b 
      run: |
           echo 1b

  mimtestC:
    runs-on: ubuntu-latest
    steps:
    - name: s1c 
      run: |
           echo 1c
    - name: s2c 
      run: echo "eu s2c citesc din s2a ENV...${{ steps.s2a.outputs.URLSERV }}"
    - name: s3c
      run: echo "eu sunt ecoul lui s3c"
      
      
