name: mimpid
run-name: PLLLmim executed by ${{ github.actor }}
on: workflow_dispatch
jobs:
  mimbuildA:
    runs-on: ubuntu-latest
    steps:
    - name: s1a 
      run: |
           echo 1a
           echo ${{ env.PIPE }}
           echo `ls -al`
    - name: Checkout
      uses: actions/checkout@v2
    - name: spin the sheeet
      uses: ./ # Uses an action in the root directory
    - name: s399a 
      run: echo "eu s3a citesc din s2a ENV...${{ steps.s2a.outputs.URLSERV}}"
       
